apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/your-dockerhub-username/main-api-server
  newName: docker.io/jheon340/main-api-server
  newTag: 832f8aa
