apiVersion: v1
kind: Service
metadata:
  name: main-api-server
  labels:
    app: main-api-server
spec:
  type: NodePort
  selector:
    app: main-api-server
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
