apiVersion: v1 # API의 버전
kind: Service

metadata:
  name: main-api-server # 이 서비스 리소스의 고유 이름
  labels:
    app: main-api-server # 이 리소스의 라벨

spec:
  type: NodePort # 외부 컴퓨터에서 클러스터 내부 파드에 접속할 수 있도록 포트를 외부에 개방
  selector:
    app: main-api-server # 이 서비스가 트래픽을 분산해서 보내줄 목적지 파드들의 라벨 대상을 지정
  ports:
    - name: http # 이 포트 매핑 설정의 이름을 'http'로 지정
      port: 80 # 서비스의 포트
      targetPort: http # 서비스가 트래픽을 전달할 파드의 포트(위에 설정한 디플로이먼트의 http 즉, 8080)
      nodePort: 30080 # 외부 컴퓨터에서 클러스터에 접속 시 사용할 포트